---
name: CD - Production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI - Main"]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-cd-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    environment:
      name: production
      url: http://localhost:8000

    steps:

      - name: Health Check
        run: |
          sleep 5
