---
# pre-commit install --allow-missing-config
# pre-commit autoupdate
# pre-commit run --all-files --color auto
exclude: |
  (?x)^(
    \.pre-commit-config\.yaml$
  )
fail_fast: true
default_stages:
  - pre-commit
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.0
    hooks:
      - id: commitizen
        name: "commitizen | validate commit messages"
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: "git | block large files"
        args: [--maxkb=2048]
      - id: check-json
        name: "general | check JSON files"
        stages:
          - manual
      - id: end-of-file-fixer
        name: "general | fix end of file"
      - id: mixed-line-ending
        name: "general | fix line ending"
        args:
          - --fix=auto
      - id: trailing-whitespace
        name: "general | remove trailing whitespace"
      - id: pretty-format-json
        name: "general | prettify JSON files"
        args:
          - --autofix
          - --no-ensure-ascii
        stages:
          - manual
  - repo: local
    hooks:
      - id: pin-github-action
        name: "security | gh-action: pinned sha"
        verbose: true
        files: ^\.github/workflows/[^/]+\.ya?ml$
        entry: "pin-github-action ."
        args:
          - --allow
          - "irishlab-io/*"
        language: node
        additional_dependencies:
          - pin-github-action@3.4.0
        stages:
          - manual
