---
name: CI - Branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
      - feat/*
      - fix/*
      - rel/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  SNYK_VERSION: "1.1300.2"
  SNYK_DELTA: "1.12.7"

jobs:

  secret:
    name: Secret Scanning
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: GitGuardian scan
        id: ggshield_scan
        uses: GitGuardian/ggshield/actions/secret@2dd7325ccac6747b28a1b427983e95163603a02e # v1.44.1
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        continue-on-error: true

      - name: Check status of potentially failing step and issue warning
        if: steps.ggshield_scan.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential secrets in the code. Please review the scan report above."
        shell: bash

  build:
    needs:
      - secret
    name: Build & Unit Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        node-version: [18]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run NPM Install CI
        run: |
          npm install ci
        shell: bash

      - name: Run Unit Test
        run: |
          echo Run Unit Test
        shell: bash

  scan:
    needs:
      - build
    name: Vulnerabilities Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18

      - name: Setup Snyk CLI
        run: |
          npm i -g snyk@${{ env.SNYK_VERSION }} snyk-delta@${{ env.SNYK_DELTA }}
          snyk auth ${{ secrets.SNYK_GH_RUNNER }}
        shell: bash

      - name: Run NPM Install CI
        run: |
          npm install ci
        shell: bash

      - name: Snyk SAST
        id: snyk_sast
        run: |
          snyk code test --severity-threshold=high --include-ignores
        shell: bash
        continue-on-error: true

      - name: Snyk SCA
        id: snyk_sca
        run: |
          snyk test --severity-threshold=high --include-ignores
        shell: bash
        continue-on-error: true

      - name: Check status of potentially failing step and issue warning
        if: steps.snyk_sast.outcome == 'failure' || steps.snyk_sca.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential vulnerabilities in the code. Please review the scan report above."
        shell: bash
