---
name: CD - Production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI - Main"]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-cd-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Production
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    environment:
      name: Production
      url: https://bank.mighty-muffin.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e

            # quick test for docker version
            docker version
          EOF

      - name: Health Check
        run: |
          sleep 20
          curl -f $url || (echo "Health check failed" && exit 1)
