---
name: Release
run-name: Release ${{ github.ref_name }} by ${{ github.actor }}

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Read changelog entry for ${{ github.ref_name }}
        id: changelog
        uses: anmarkoulis/commitizen-changelog-reader@0d1f06b1c3de81073cf4168c227268c6dd2bfa04 # v1.2.0
        with:
          tag_name: ${{ github.ref_name }}
          changelog: CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          body: ${{ join(fromJSON(steps.changelog.outputs.release_notes), '') }}
          token: ${{ secrets.GH_PUSH_TOKEN }}
          draft: false
          prerelease: false
